### ISSUE TITLE
Precompiled for download

### ISSUE THREAD

**Issue by probonopd** [chigraph/precompiled-kf5-linux#1]
Will this be available precompiled for download?

**Comment by russelltg** [comment]
Yes. I've been working on a travis script to upload it automatically.

**Comment by russelltg** [comment]
Done! It took too long for a travis-ci job, so I compiled them on my computer. 

https://github.com/chigraph/precompiled-kf5-linux/releases/tag/precompiled

**Comment by probonopd** [comment]
Thank you very much, highly appreciated.

**Comment by sigoa** [comment]
those precompiled ones are quite handy: not only saves it compile-time but often it does not build at all due to gazillions of potential errors
