### ISSUE TITLE
Document how to use

### ISSUE THREAD

**Issue by probonopd** [chigraph/precompiled-kf5-linux#2]
Sorry if this is a very basic question, but how do you use this? Are there some environment variables that need to be set for the build toolchain to pick these up?

**Comment by probonopd** [comment]
Managed to compile an application that uses KF5:
https://github.com/probonopd/imagewriter/blob/master/.travis.yml

But there is probably a better way to do it?

Especially, how to use the extra-cmake-modules that comes with it?

**Comment by probonopd** [comment]
Also using it here:
https://github.com/probonopd/hotspot/blob/patch-1/.travis.yml

Am I using it correctly?

**Comment by russelltg** [comment]
Closing this unless there are issues
